import { readFile } from 'node:fs/promises';
async function secret(file,fallback=''){if(!file)return fallback;return(await readFile(file,'utf8')).trim();}
export class ClickHouseClient{
  constructor({url,user='default',password='',passwordFile=''}){this.url=url.replace(/\/$/,'');this.user=user;this.password=password;this.passwordFile=passwordFile;}
  async initialize(){this.password=await secret(this.passwordFile,this.password);}
  #headers(contentType='text/plain'){const h={'content-type':contentType};if(this.user)h.authorization=`Basic ${Buffer.from(`${this.user}:${this.password}`).toString('base64')}`;return h;}
  async query(sql,body=''){const response=await fetch(`${this.url}/?query=${encodeURIComponent(sql)}`,{method:'POST',headers:this.#headers(body?'application/x-ndjson':'text/plain'),body});if(!response.ok)throw new Error(`CLICKHOUSE_${response.status}:${(await response.text()).slice(0,500)}`);return response.text();}
  async ping(){await this.query('SELECT 1');return true;}
  async insert(table,rows){if(!rows.length)return;const body=`${rows.map(r=>JSON.stringify(r)).join('\n')}\n`;await this.query(`INSERT INTO ${table} FORMAT JSONEachRow`,body);}
}
export function landingRow(entry){const {envelope,mapping,receivedAt,trustedContext}=entry.record;return {tenant_id:mapping.tenantId,project_id:mapping.projectId,environment:mapping.environment,mapping_version:mapping.mappingVersion,policy_version:mapping.policyVersion,source_system:'smpp',source_product:mapping.sourceProduct,source_record_id:envelope.recordId,source_record_hash:envelope.recordHash,source_schema_name:'ProviderOpsEnvelope',source_schema_version:envelope.schemaVersion,record_type:envelope.recordType,priority:String(envelope.priority??'P2'),runtime_instance_id:envelope.instanceId,deployment_id:trustedContext.deploymentId,collector_id:trustedContext.collectorId,provider_id:envelope.providerId,provider_instance_id:envelope.instanceId,task_id:envelope.taskId??null,resource_id:envelope.resourceId??null,operation_name:envelope.operationName??null,correlation_id:envelope.correlationId??envelope.attributes?.correlationId??null,causation_record_id:envelope.causationRecordId??envelope.attributes?.causationRecordId??null,trace_id:envelope.attributes?.traceId??envelope.attributes?.correlation?.traceId??null,span_id:envelope.attributes?.spanId??envelope.attributes?.correlation?.spanId??null,occurred_at:envelope.occurredAt,emitted_at:envelope.emittedAt,received_at:receivedAt,ingested_at:new Date().toISOString(),attributes_json:JSON.stringify(envelope.attributes??{}),payload_json:JSON.stringify(envelope.payload??null),envelope_json:JSON.stringify(envelope),wal_segment:entry.segment,wal_offset:entry.offset,ingest_version:Date.now()};}
export function canonicalRow(fact){return {fact_id:fact.factId,fact_hash:fact.factHash,fact_type:fact.factType,fact_version:fact.factVersion,source_system:fact.sourceSystem,source_product:fact.sourceProduct,source_record_id:fact.sourceRecordId,source_record_hash:fact.sourceRecordHash,source_schema_name:fact.sourceSchemaName,source_schema_version:fact.sourceSchemaVersion,tenant_id:fact.tenantId,project_id:fact.projectId,environment:fact.environment,source_instance_urn:fact.sourceInstanceUrn,occurred_at:fact.occurredAt,received_at:fact.receivedAt,normalized_at:fact.normalizedAt,entity_refs_json:JSON.stringify(fact.entityRefs),relations_json:JSON.stringify(fact.relations),correlation_json:JSON.stringify(fact.correlation),payload_json:JSON.stringify(fact.payload),normalizer_id:fact.provenance.normalizerId,normalizer_version:fact.provenance.normalizerVersion,mapping_version:fact.provenance.mappingVersion,policy_version:fact.provenance.policyVersion};}
