import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
const root=new URL(`file://${process.cwd()}/`);
test('one-click deployment assets exist and include all containers',async()=>{
  const compose=await readFile(new URL('compose.yaml',root),'utf8');
  for(const service of ['clickhouse:','telemetry-migrate:','telemetry-processor:','otel-collector:','query-api:','grafana:']) assert.match(compose,new RegExp(`\\n  ${service}`));
  assert.match(compose,/config\/generated\/source-mappings\.json/);
  assert.match(compose,/service_completed_successfully/);
  assert.match(compose,/TELEMETRY_BIND_ADDRESS/);
  assert.match(compose,/\$\{OTLP_HTTP_BIND_ADDRESS:-0\.0\.0\.0\}:\$\{OTLP_HTTP_PORT:-4318\}:4318/);
  assert.match(compose,/platform: linux\/arm64/);
  assert.match(compose,/dockerfile: clickhouse-arm64\/Dockerfile/);
  assert.match(compose,/image: smpp-telemetry-clickhouse:25\.3\.14\.14-arm64v8-source/);
  assert.match(compose,/pull_policy: never/);
  assert.doesNotMatch(compose,/image: clickhouse\/clickhouse-server/);
  assert.doesNotMatch(compose,/ports: \["\$\{OTLP_GRPC_PORT/);
  const packagedCompose=await readFile(new URL('deploy/compose/compose.yaml',root),'utf8');
  assert.equal(packagedCompose,compose,'deployment compose copy must match the root compose exactly');
  assert.match(compose,/WAL_MAX_PENDING_WRITES/);
  assert.match(compose,/PROCESSOR_SHUTDOWN_TIMEOUT_MS/);
  const processorDockerfile=await readFile(new URL('telemetry-processor/Dockerfile',root),'utf8');
  assert.match(processorDockerfile,/COPY contracts \.\/dist\/contracts/);
  const clickhouseDockerfile=await readFile(new URL('clickhouse-arm64/Dockerfile',root),'utf8');
  assert.match(clickhouseDockerfile,/CLICKHOUSE_SOURCE_REF=v25\.3\.14\.14-lts/);
  assert.match(clickhouseDockerfile,/CLICKHOUSE_SOURCE_COMMIT=84d6b30ad528e77d787ab7a2437406c1e2a5887a/);
  assert.match(clickhouseDockerfile,/-DNO_ARMV81_OR_HIGHER=ON/);
  assert.match(clickhouseDockerfile,/-DARCH_NATIVE=OFF/);
  assert.match(clickhouseDockerfile,/-DCOMPILER_CACHE=disabled/);
  assert.match(clickhouseDockerfile,/--target clickhouse-stripped/);
  assert.match(clickhouseDockerfile,/clickhouse extract-from-config/);
  assert.match(clickhouseDockerfile,/test "\$\{TARGETARCH\}" = arm64/);
  assert.match(clickhouseDockerfile,/clickhouse-25\.3\.14\.14-complete-source\.tar\.zst/);
  assert.match(clickhouseDockerfile,/sha256sum --check/);
  assert.match(clickhouseDockerfile,/\.clickhouse-source-revision/);
  assert.match(clickhouseDockerfile,/ROOT_PATH="\/src"/);
  assert.match(clickhouseDockerfile,/StorageSystemLicenses\.sh > \/tmp\/StorageSystemLicenses\.generated\.cpp/);
  assert.match(clickhouseDockerfile,/smpp-clickhouse-25\.3\.14\.14-arm64-build/);
  assert.match(clickhouseDockerfile,/cp \/src\/build\/programs\/clickhouse-stripped \/out\/clickhouse/);
  assert.match(clickhouseDockerfile,/mkdir -p \/docker-entrypoint-initdb\.d \/etc\/clickhouse-client/);
  assert.doesNotMatch(clickhouseDockerfile,/\bgit (?:clone|fetch)\b/);
  assert.doesNotMatch(clickhouseDockerfile,/clickhouse\/clickhouse-server/);
  const sourcePackager=await readFile(new URL('tools/prepare-clickhouse-source.sh',root),'utf8');
  assert.match(sourcePackager,/submodule update --init --recursive --depth 1/);
  assert.match(sourcePackager,/submodule foreach --quiet --recursive/);
  assert.match(sourcePackager,/contrib\/icudata\/icudt78l_dat\.S/);
  assert.match(sourcePackager,/SOURCE_COMMIT=84d6b30ad528e77d787ab7a2437406c1e2a5887a/);
  assert.match(sourcePackager,/--exclude='\*\/\.git'/);
  await access(new URL('deploy.sh',root));
  await access(new URL('clickhouse-arm64/preflight.sh',root));
  await access(new URL('docs/SMPP_%E9%81%A5%E6%B5%8B%E5%B9%B3%E5%8F%B0%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md',root));
});
test('ClickHouse DateTime64 retention expressions are compatible with the pinned image',async()=>{
  for(const name of ['003_landing.sql','005_core.sql']){
    const sql=await readFile(new URL(`telemetry-schema/migrations/${name}`,root),'utf8');
    assert.match(sql,/TTL toDateTime\(/);
    assert.doesNotMatch(sql,/TTL (?:occurred_at|received_at) \+/);
  }
});
test('projection target output includes standalone and SDAR shadow targets',async()=>{
  const cfg=JSON.parse(await readFile(new URL('config/projection-targets.example.json',root),'utf8'));
  assert.equal(cfg.targets.find(x=>x.targetId==='standalone-smpp')?.enabled,true);
  assert.equal(cfg.targets.find(x=>x.targetId==='sdar-warehouse-shadow')?.enabled,false);
});
test('x86_64 development override replaces only the ClickHouse build path',async()=>{
  const example=await readFile(new URL('.env.example',root),'utf8');
  const override=await readFile(new URL('deploy/development/compose.x86_64.override.yaml',root),'utf8');
  assert.match(example,/^SMPP_SOURCE_ID=[A-Za-z0-9][A-Za-z0-9._:-]+$/m);
  const qualificationExample=await readFile(new URL('deploy/stable-smpp-integration/.env.example',root),'utf8');
  assert.match(qualificationExample,/^SMPP_SOURCE_ID=smpp\.production\.ugv-direct$/m);
  assert.match(override,/image: clickhouse\/clickhouse-server:25\.3\.14\.14/);
  assert.match(override,/platform: linux\/amd64/);
  assert.match(override,/build: !reset null/);
  assert.match(override,/pull_policy: missing/);
  assert.match(override,/otel-collector:[\s\S]*host\.docker\.internal:host-gateway/);
  assert.doesNotMatch(override,/telemetry-processor:|query-api:|grafana:/);
});
