"""Derive the Processor's explicit column contract from additive local migrations."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[2]
tables={}
def split_top(value):
    parts=[];start=depth=0;quote=None
    for i,char in enumerate(value):
        if quote:
            if char==quote and (i==0 or value[i-1]!='\\'):quote=None
        elif char in "'\"`":quote=char
        elif char=='(':depth+=1
        elif char==')':depth-=1
        elif char==',' and depth==0:parts.append(value[start:i].strip());start=i+1
    parts.append(value[start:].strip());return parts
def closing(sql,start):
    depth=1;quote=None
    for i in range(start,len(sql)):
        char=sql[i]
        if quote:
            if char==quote and sql[i-1]!='\\':quote=None
        elif char in "'\"`":quote=char
        elif char=='(':depth+=1
        elif char==')':
            depth-=1
            if depth==0:return i
    raise ValueError('unclosed table DDL')
def column(value):
    match=re.match(r'(\w+)\s+(.+)',value,re.S)
    if not match:raise ValueError(value)
    name,type_=match.groups();type_=re.split(r'\s+(?:DEFAULT|CODEC|COMMENT|AFTER|FIRST)\b',type_,maxsplit=1)[0].strip()
    return name,type_
for path in sorted((root/'telemetry-schema/migrations').glob('*.sql')):
    sql=path.read_text()
    for match in re.finditer(r'CREATE TABLE IF NOT EXISTS ((?:telemetry_landing|telemetry_normalized|telemetry_core|telemetry_query)\.\w+|telemetry_meta\.(?:projection_dead_letter|provider_quality_observation_v1))\s*\(',sql):
        tables[match[1]]=dict(column(item) for item in split_top(sql[match.end():closing(sql,match.end())]))
    for match in re.finditer(r'ALTER TABLE (\w+\.\w+) ADD COLUMN IF NOT EXISTS ([^;]+);',sql):
        if match[1] in tables:
            key,value=column(match[2]);tables[match[1]][key]=value
out=root/'telemetry-processor/src/packages/exporters/standalone-contract.ts'
out.write_text('// Generated by telemetry-schema/tools/generate-standalone-contract.py; do not hand edit.\nexport const STANDALONE_SCHEMA: Readonly<Record<string, Readonly<Record<string,string>>>> = '+json.dumps(tables,indent=2)+';\n')
print(f'{len(tables)} table contracts generated')
