import { mkdir, open, readdir, readFile, rename, stat, truncate } from 'node:fs/promises';
import { join } from 'node:path';
import { crc32c } from './crc32c.js';
const HEADER=4, TRAILER=4; const segmentName=id=>`segment-${String(id).padStart(12,'0')}.wal`;
async function fsyncDirectory(path){ const dir=await open(path,'r'); try{await dir.sync();}finally{await dir.close();} }
export class WalStore {
  constructor({directory,segmentMaxBytes=64*1024*1024}){ this.directory=directory; this.segmentMaxBytes=segmentMaxBytes; this.entries=[]; this.dedup=new Map(); this.currentSegment=1; this.currentSize=0; this.totalBytes=0; this.checkpoints={}; }
  async initialize(){ await mkdir(this.directory,{recursive:true}); await this.#loadCheckpoints(); const names=(await readdir(this.directory)).filter(n=>/^segment-\d+\.wal$/.test(n)).sort(); if(!names.length){await this.#createSegment(1);return;} for(const name of names) await this.#scanSegment(name); this.currentSegment=Number(names.at(-1).match(/\d+/)[0]); this.currentSize=(await stat(join(this.directory,names.at(-1)))).size; this.totalBytes=0; for(const n of names)this.totalBytes+=(await stat(join(this.directory,n))).size; }
  async #loadCheckpoints(){ try{this.checkpoints=JSON.parse(await readFile(join(this.directory,'checkpoints.json'),'utf8'));}catch{this.checkpoints={};} }
  async #createSegment(id){ const path=join(this.directory,segmentName(id)); const file=await open(path,'a'); await file.sync(); await file.close(); await fsyncDirectory(this.directory); this.currentSegment=id; this.currentSize=0; }
  async #scanSegment(name){ const id=Number(name.match(/\d+/)[0]), path=join(this.directory,name), data=await readFile(path); let offset=0; while(offset<data.length){ if(offset+HEADER>data.length){await truncate(path,offset);break;} const length=data.readUInt32BE(offset), end=offset+HEADER+length+TRAILER; if(length>16*1024*1024||end>data.length){await truncate(path,offset);break;} const payload=data.subarray(offset+HEADER,offset+HEADER+length), expected=data.readUInt32BE(offset+HEADER+length); if(crc32c(payload)!==expected){if(end===data.length){await truncate(path,offset);break;} throw new Error(`WAL_CRC_MISMATCH:${name}:${offset}`);} const record=JSON.parse(payload.toString('utf8')); const entry={segment:id,offset,offsetEnd:end,record}; this.entries.push(entry); if(record.kind==='accepted') this.dedup.set(`${record.sourceSystem}:${record.envelope.recordId}`,record.envelope.recordHash); offset=end; } }
  classify(sourceSystem,recordId,recordHash){ const existing=this.dedup.get(`${sourceSystem}:${recordId}`); if(existing===undefined)return'new'; return existing===recordHash?'duplicate':'conflict'; }
  acceptedHash(sourceSystem,recordId){ return this.dedup.get(`${sourceSystem}:${recordId}`); }
  async append(record){ const payload=Buffer.from(JSON.stringify(record),'utf8'), frame=Buffer.allocUnsafe(HEADER+payload.length+TRAILER); frame.writeUInt32BE(payload.length,0); payload.copy(frame,HEADER); frame.writeUInt32BE(crc32c(payload),HEADER+payload.length); if(this.currentSize>0&&this.currentSize+frame.length>this.segmentMaxBytes)await this.#createSegment(this.currentSegment+1); const path=join(this.directory,segmentName(this.currentSegment)), offset=this.currentSize; const file=await open(path,'a'); try{await file.write(frame);await file.sync();}finally{await file.close();} this.currentSize+=frame.length; this.totalBytes+=frame.length; const entry={segment:this.currentSegment,offset,offsetEnd:this.currentSize,record}; this.entries.push(entry); if(record.kind==='accepted')this.dedup.set(`${record.sourceSystem}:${record.envelope.recordId}`,record.envelope.recordHash); return entry; }
  checkpoint(id){ return this.checkpoints[id]??{segment:0,offsetEnd:0}; }
  pending(id,limit=200){ const cp=this.checkpoint(id); return this.entries.filter(e=>e.segment>cp.segment||(e.segment===cp.segment&&e.offsetEnd>cp.offsetEnd)).slice(0,limit); }
  async commit(id,entry){ const next={segment:entry.segment,offsetEnd:entry.offsetEnd,updatedAt:new Date().toISOString()}; const all={...this.checkpoints,[id]:next}, temp=join(this.directory,`checkpoints.${process.pid}.tmp`), target=join(this.directory,'checkpoints.json'); const file=await open(temp,'w',0o600); try{await file.writeFile(JSON.stringify(all,null,2));await file.sync();}finally{await file.close();} await rename(temp,target); await fsyncDirectory(this.directory); this.checkpoints=all; }
  stats(){ return {segments:new Set(this.entries.map(e=>e.segment)).size||1,entries:this.entries.length,totalBytes:this.totalBytes,currentBytes:this.currentSize,checkpoints:this.checkpoints,pendingByCheckpoint:Object.fromEntries(Object.keys(this.checkpoints).map(id=>[id,this.pending(id,Number.MAX_SAFE_INTEGER).length]))}; }
}
