import { readFile } from 'node:fs/promises';
const int=(name:string,fallback:number)=>{const v=Number(process.env[name]??fallback);if(!Number.isFinite(v))throw new Error(`${name}_INVALID`);return v;};
const positiveInt=(name:string,fallback:number)=>{const v=int(name,fallback);if(!Number.isSafeInteger(v)||v<1)throw new Error(`${name}_INVALID`);return v;};
const bool=(name:string,fallback=false)=>{const value=String(process.env[name]??fallback).toLowerCase();if(!['true','false'].includes(value))throw new Error(`${name}_INVALID`);return value==='true';};
const nonnegativeInt=(name:string,fallback:number)=>{const value=int(name,fallback);if(!Number.isSafeInteger(value)||value<0)throw new Error(`${name}_INVALID`);return value;};
const fraction=(name:string,fallback:number)=>{const value=int(name,fallback);if(value<=0||value>1)throw new Error(`${name}_INVALID`);return value;};
const port=()=>{const value=positiveInt('PROCESSOR_PORT',8443);if(value>65535)throw new Error('PROCESSOR_PORT_INVALID');return value;};
async function secretValue(name:string,fallback=''){const file=process.env[`${name}_FILE`];if(file)return(await readFile(file,'utf8')).trim();return process.env[name]??fallback;}
export async function loadConfig(){return {host:process.env.PROCESSOR_HOST??'0.0.0.0',port:port(),maxRequestBytes:positiveInt('MAX_REQUEST_BYTES',4*1024*1024),walMinFreeBytes:nonnegativeInt('WAL_MIN_FREE_BYTES',64*1024*1024),walCacheMaxBytes:positiveInt('WAL_CACHE_MAX_BYTES',8*1024*1024),walArchiveDir:process.env.WAL_ARCHIVE_DIR,walGcEnabled:bool('WAL_GC_ENABLED',false),walMaintenanceIntervalMs:positiveInt('WAL_MAINTENANCE_INTERVAL_MS',60000),replayTargetsFile:process.env.REPLAY_TARGETS_FILE,walDir:process.env.WAL_DIR??'./var/wal',walSegmentMaxBytes:positiveInt('WAL_SEGMENT_MAX_BYTES',64*1024*1024),walMaxBytes:positiveInt('WAL_MAX_BYTES',10*1024*1024*1024),walMaxPendingWrites:positiveInt('WAL_MAX_PENDING_WRITES',1024),walRejectThreshold:fraction('WAL_REJECT_THRESHOLD',0.98),exportBatchSize:positiveInt('EXPORT_BATCH_SIZE',200),exportIntervalMs:positiveInt('EXPORT_INTERVAL_MS',1000),shutdownTimeoutMs:positiveInt('PROCESSOR_SHUTDOWN_TIMEOUT_MS',10000),sourceMappingsFile:process.env.SOURCE_MAPPINGS_FILE??'./config/source-mappings.json',projectionTargetsFile:process.env.PROJECTION_TARGETS_FILE??'./config/projection-targets.json',requireCollectorId:bool('PROCESSOR_REQUIRE_COLLECTOR_ID',true),allowedCollectorIds:String(process.env.PROCESSOR_ALLOWED_COLLECTOR_IDS??'smpp-gateway-1').split(',').map(x=>x.trim()).filter(Boolean),adminApiKey:await secretValue('PROCESSOR_ADMIN_API_KEY',''),tls:{mode:process.env.PROCESSOR_TLS_MODE??'disabled',caFile:process.env.PROCESSOR_TLS_CA_FILE??'',certFile:process.env.PROCESSOR_TLS_CERT_FILE??'',keyFile:process.env.PROCESSOR_TLS_KEY_FILE??''}};}
export async function loadTls(config:{mode:string;caFile:string;certFile:string;keyFile:string}){if(config.mode!=='required')return null;if(!config.caFile||!config.certFile||!config.keyFile)throw new Error('TLS_FILES_REQUIRED');return{ca:await readFile(config.caFile),cert:await readFile(config.certFile),key:await readFile(config.keyFile),requestCert:true,rejectUnauthorized:true};}
