import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location("release_version", Path(__file__).with_name("release-version.py"))
release = importlib.util.module_from_spec(spec)
spec.loader.exec_module(release)


class ReleaseVersionTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="smpp-clickhouse-version-")
        self.root = Path(self.tmp.name)
        (self.root / "cmake").mkdir()
        (self.root / ".clickhouse-source-revision").write_text(release.SOURCE_COMMIT + "\n")
        self.versions = self.root / "cmake/autogenerated_versions.txt"
        self.versions.write_bytes(release.UPSTREAM)

    def tearDown(self):
        self.tmp.cleanup()

    def binary(self, version="25.3.14.14", commit=release.SOURCE_COMMIT, official=False):
        path = self.root / "clickhouse-test-double"
        rows = {"VERSION_FULL": "ClickHouse 25.3.14.14", "VERSION_GITHASH": commit, "VERSION_DESCRIBE": release.SOURCE_REF}
        data = json.dumps({"data": [{"name": key, "value": value} for key, value in rows.items()]})
        path.write_text("#!/usr/bin/env python3\nimport sys\nprint(" + repr(f"ClickHouse local version {version}" + (" (official build)" if official else "") + ".") + " if sys.argv[1]=='--version' else " + repr(data) + ")\n")
        path.chmod(0o700)
        return path

    def test_fixed_source_release_metadata_is_materialized_idempotently(self):
        first = release.prepare(self.root)
        self.assertEqual(self.versions.read_bytes(), release.PREPARED)
        self.assertEqual(release.prepare(self.root), first)
        self.assertEqual(json.loads((self.root / ".clickhouse-release-version.json").read_text()), first)

    def test_wrong_source_commit_cannot_be_relabelled(self):
        (self.root / ".clickhouse-source-revision").write_text("0" * 40)
        with self.assertRaisesRegex(ValueError, "SOURCE_COMMIT_MISMATCH"):
            release.prepare(self.root)
        self.assertEqual(self.versions.read_bytes(), release.UPSTREAM)

    def test_unknown_version_metadata_cannot_be_relabelled(self):
        self.versions.write_bytes(release.UPSTREAM.replace(b"54509", b"54510"))
        with self.assertRaisesRegex(ValueError, "UNRECOGNIZED"):
            release.prepare(self.root)

    def test_binary_gate_accepts_exact_release_identity(self):
        for official in [False, True]:
            self.assertEqual(release.verify_binary(self.binary(official=official))["VERSION_GITHASH"], release.SOURCE_COMMIT)

    def test_binary_gate_rejects_the_observed_stale_release(self):
        with self.assertRaisesRegex(ValueError, "BINARY_VERSION_MISMATCH"):
            release.verify_binary(self.binary(version="25.3.14.1"))

    def test_binary_gate_rejects_correct_version_with_wrong_source_commit(self):
        with self.assertRaisesRegex(ValueError, "BUILD_IDENTITY_MISMATCH"):
            release.verify_binary(self.binary(commit="0" * 40))


if __name__ == "__main__":
    unittest.main()
