#!/usr/bin/env python3
"""Materialize release metadata omitted from the fixed upstream source tree.

Upstream tests/ci/version_helper.py updates these three generated values for a
release. The committed file at 84d6b30 still describes 25.3.14.1; -D overrides
cannot fix it because cmake/version.cmake includes the generated SET values.
"""
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

SOURCE_COMMIT = "84d6b30ad528e77d787ab7a2437406c1e2a5887a"
SOURCE_REF = "v25.3.14.14-lts"
VERSION = "25.3.14.14"
UPSTREAM_SHA256 = "a3138cf12102a553e4a4886af83ca8af38df169e27262f529998e2178a97da37"
UPSTREAM = b"""# This variables autochanged by tests/ci/version_helper.py:

# NOTE: VERSION_REVISION has nothing common with DBMS_TCP_PROTOCOL_VERSION,
# only DBMS_TCP_PROTOCOL_VERSION should be incremented on protocol changes.
SET(VERSION_REVISION 54509)
SET(VERSION_MAJOR 25)
SET(VERSION_MINOR 3)
SET(VERSION_PATCH 14)
SET(VERSION_GITHASH d6202689cb5af95ff6e44f27ee892381b12f8279)
SET(VERSION_DESCRIBE v25.3.14.1-lts)
SET(VERSION_STRING 25.3.14.1)
# end of autochange
"""
assert hashlib.sha256(UPSTREAM).hexdigest() == UPSTREAM_SHA256
PREPARED = UPSTREAM
for name, value in (("VERSION_GITHASH", SOURCE_COMMIT), ("VERSION_DESCRIBE", SOURCE_REF), ("VERSION_STRING", VERSION)):
    PREPARED, count = re.subn(rb"SET\(" + name.encode() + rb" [^)]+\)", f"SET({name} {value})".encode(), PREPARED)
    assert count == 1


def prepare(source: Path) -> dict[str, str]:
    marker = source / ".clickhouse-source-revision"
    versions = source / "cmake/autogenerated_versions.txt"
    if marker.is_symlink() or versions.is_symlink():
        raise ValueError("SOURCE_VERSION_SYMLINK_FORBIDDEN")
    if marker.read_text().strip() != SOURCE_COMMIT:
        raise ValueError("CLICKHOUSE_SOURCE_COMMIT_MISMATCH")
    if versions.read_bytes() not in (UPSTREAM, PREPARED):
        raise ValueError("CLICKHOUSE_UNRECOGNIZED_GENERATED_VERSION_METADATA")
    versions.write_bytes(PREPARED)
    proof = {
        "sourceCommit": SOURCE_COMMIT,
        "sourceRef": SOURCE_REF,
        "version": VERSION,
        "upstreamGeneratedVersionSha256": UPSTREAM_SHA256,
        "preparedGeneratedVersionSha256": hashlib.sha256(PREPARED).hexdigest(),
    }
    (source / ".clickhouse-release-version.json").write_text(json.dumps(proof, indent=2) + "\n")
    return proof


def verify_binary(binary: Path) -> dict[str, str]:
    binary = binary.resolve(strict=True)
    def run(*args: str) -> str:
        return subprocess.run([str(binary), *args], check=True, text=True, capture_output=True, timeout=60).stdout
    reported = run("--version").strip()
    if not re.fullmatch(r"ClickHouse (?:local|server) version 25\.3\.14\.14(?: \(official build\))?\.", reported):
        raise ValueError(f"CLICKHOUSE_BINARY_VERSION_MISMATCH:{reported}")
    query = "SELECT name,value FROM system.build_options WHERE name IN ('VERSION_FULL','VERSION_GITHASH','VERSION_DESCRIBE') FORMAT JSON"
    rows = json.loads(run("local", "--query", query))["data"]
    actual = {row["name"]: row["value"] for row in rows}
    expected = {"VERSION_FULL": f"ClickHouse {VERSION}", "VERSION_GITHASH": SOURCE_COMMIT, "VERSION_DESCRIBE": SOURCE_REF}
    if actual != expected:
        raise ValueError(f"CLICKHOUSE_BINARY_BUILD_IDENTITY_MISMATCH:{json.dumps(actual, sort_keys=True)}")
    return {"versionOutput": reported, **actual}


if __name__ == "__main__":
    if len(sys.argv) != 3 or sys.argv[1] not in ("prepare", "verify-binary"):
        raise SystemExit("usage: release-version.py prepare SOURCE | verify-binary BINARY")
    result = prepare(Path(sys.argv[2])) if sys.argv[1] == "prepare" else verify_binary(Path(sys.argv[2]))
    print(json.dumps(result, sort_keys=True))
